services:
  - type: web
    name: altitude-bpo-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class -w 1 app:socketio
    envVars:
      - key: SECRET_KEY
        generateValue: true